/*
export {constants} from '../../chris-premades/scripts/lib/constants.js';
export {activityUtils} from '../../chris-premades/scripts/lib/utilities/activityUtils.js';
export {actorUtils} from '../../chris-premades/scripts/lib/utilities/actorUtils.js';
export {devUtils} from '../../chris-premades/scripts/lib/utilities/devUtils.js';
export {dialogUtils} from '../../chris-premades/scripts/lib/utilities/dialogUtils.js';
export {effectUtils} from '../../chris-premades/scripts/lib/utilities/effectUtils.js';
export {genericUtils} from '../../chris-premades/scripts/lib/utilities/genericUtils.js';
export {itemUtils} from '../../chris-premades/scripts/lib/utilities/itemUtils.js';
export {rollUtils} from '../../chris-premades/scripts/lib/utilities/rollUtils.js';
export {socketUtils} from '../../chris-premades/scripts/lib/utilities/socketUtils.js';
export {templateUtils} from '../../chris-premades/scripts/lib/utilities/templateUtils.js';
export {workflowUtils} from '../../chris-premades/scripts/lib/utilities/workflowUtils.js';
export {errors} from '../../chris-premades/scripts/lib/errors.js';
export {animationUtils} from '../../chris-premades/scripts/lib/utilities/animationUtils.js';
export {tokenUtils} from '../../chris-premades/scripts/lib/utilities/tokenUtils.js';
export {compendiumUtils} from '../../chris-premades/scripts/lib/utilities/compendiumUtils.js';
export {combatUtils} from '../../chris-premades/scripts/lib/utilities/combatUtils.js';
export {crosshairUtils} from '../../chris-premades/scripts/lib/utilities/crosshairUtils.js';
export {spellUtils} from '../../chris-premades/scripts/lib/utilities/spellUtils.js';
export {regionUtils} from '../../chris-premades/scripts/lib/utilities/regionUtils.js';
export {macroUtils} from '../../chris-premades/scripts/lib/utilities/macroUtils.js';
export {thirdPartyUtils} from '../../chris-premades/scripts/lib/utilities/thirdPartyUtils.js';
export {Crosshairs} from '../../chris-premades/scripts/lib/crosshairs.js';
export {Summons} from '../../chris-premades/scripts/lib/summons.js';
export {Teleport} from '../../chris-premades/scripts/lib/teleport.js';
*/

export let constants = undefined;
export let errors = undefined;
export let activityUtils = undefined;
export let actorUtils = undefined;
export let devUtils = undefined;
export let dialogUtils = undefined;
export let effectUtils = undefined;
export let genericUtils = undefined;
export let itemUtils = undefined;
export let rollUtils = undefined;
export let socketUtils = undefined;
export let templateUtils = undefined;
export let workflowUtils = undefined;
export let animationUtils = undefined;
export let tokenUtils = undefined;
export let compendiumUtils = undefined;
export let combatUtils = undefined;
export let crosshairUtils = undefined;
export let spellUtils = undefined;
export let regionUtils = undefined;
export let macroUtils = undefined;
export let thirdPartyUtils = undefined;
export let Crosshairs = undefined;
export let Summons = undefined;
export let Teleport = undefined;
export function setup() {
    constants = globalThis.chrisPremades.utils.constants;
    errors = globalThis.chrisPremades.utils.errors;
    activityUtils = globalThis.chrisPremades.utils.activityUtils;
    actorUtils = globalThis.chrisPremades.utils.actorUtils;
    devUtils = globalThis.chrisPremades.utils.devUtils;
    dialogUtils = globalThis.chrisPremades.utils.dialogUtils;
    effectUtils = globalThis.chrisPremades.utils.effectUtils;
    genericUtils = globalThis.chrisPremades.utils.genericUtils;
    itemUtils = globalThis.chrisPremades.utils.itemUtils;
    rollUtils = globalThis.chrisPremades.utils.rollUtils;
    socketUtils = globalThis.chrisPremades.utils.socketUtils;
    templateUtils = globalThis.chrisPremades.utils.templateUtils;
    workflowUtils = globalThis.chrisPremades.utils.workflowUtils;
    animationUtils = globalThis.chrisPremades.utils.animationUtils;
    tokenUtils = globalThis.chrisPremades.utils.tokenUtils;
    compendiumUtils = globalThis.chrisPremades.utils.compendiumUtils;
    combatUtils = globalThis.chrisPremades.utils.combatUtils;
    crosshairUtils = globalThis.chrisPremades.utils.crosshairUtils;
    spellUtils = globalThis.chrisPremades.utils.spellUtils;
    regionUtils = globalThis.chrisPremades.utils.regionUtils;
    macroUtils = globalThis.chrisPremades.utils.macroUtils;
    thirdPartyUtils = globalThis.chrisPremades.utils.thirdPartyUtils;
    Crosshairs = globalThis.chrisPremades.Crosshairs;
    Summons = globalThis.chrisPremades.Summons;
    Teleport = globalThis.chrisPremades.Teleport;
}
